//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_vehicle
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_vehicle()
        {
            this.tbl_bike = new HashSet<tbl_bike>();
            this.tbl_Car = new HashSet<tbl_Car>();
        }
    
        public int ID { get; set; }
        public int Vehicle_type_id { get; set; }
        public string Make { get; set; }
        public int? ModelNo { get; set; }
        public string Engine { get; set; }
        public string Body_type { get; set; }
    
        public virtual tbl_vehicletype tbl_vehicletype { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_bike> tbl_bike { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Car> tbl_Car { get; set; }
    }
}
