//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tbl_Car
    {
        public int ID { get; set; }
        public int Vehicle_id { get; set; }
        [Required(ErrorMessage = "This Field is Required")]
      
        public int? Doors { get; set; }
        [Required(ErrorMessage = "This Field is Required")]
        public int? Wheels { get; set; }
        [Required(ErrorMessage = "This Field is Required")]
        public int? No_of_seat { get; set; }
    
        public virtual tbl_vehicle tbl_vehicle { get; set; }
    }
}
