//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_bike
    {
        public int ID { get; set; }
        public int Vehicle_id { get; set; }
        public string Type_of_start { get; set; }
    
        public virtual tbl_vehicle tbl_vehicle { get; set; }
    }
}
